defmodule CodexPooler.Dev.Seeds.RealTraffic do
  @moduledoc false

  import Ecto.Query

  alias CodexPooler.Access
  alias CodexPooler.Access.APIKey
  alias CodexPooler.Accounts.{Scope, User}
  alias CodexPooler.Dev.UpstreamAccountBundle.PrivateFile
  alias CodexPooler.Pools.Pool
  alias CodexPooler.Repo

  @seed_key "codex_pooler_real_traffic_seed"
  @pool_slug "dev-real-traffic"
  @pool_name "Dev Real Traffic Pool"
  @bootstrap_dir Path.join(["tmp", "dev-seed"])
  @env_path Path.join(@bootstrap_dir, "real-traffic.env")

  @spec pool_slug() :: String.t()
  def pool_slug, do: @pool_slug

  @spec env_path() :: String.t()
  def env_path, do: @env_path

  # Reruns keep the Pool and whatever was imported into it, revoke the keys an
  # earlier run minted and mint one new key, so exactly one seed key is active.
  @spec run(%{required(:owner) => User.t()}) :: map()
  def run(%{owner: owner}) do
    ensure_private_directory!()
    validate_output!()

    with_output_lock(fn -> rotate(owner) end)
  end

  # This local file lock outlives a PostgreSQL disconnect at COMMIT. A second
  # publisher cannot replace this path while confirmed rollback is compensated.
  # A hard exit or uncertain connection failure retains the lock for inspection.
  defp with_output_lock(operation) do
    lock_path = @env_path <> ".lock"

    case File.open(lock_path, [:write, :binary, :exclusive]) do
      {:ok, lock} ->
        try do
          File.chmod!(lock_path, 0o600)
          result = operation.()
          File.rm!(lock_path)

          case result do
            {:ok, result} -> result
            {:error, error, stacktrace} -> reraise error, stacktrace
          end
        after
          File.close(lock)
        end

      {:error, _reason} ->
        raise "seed output is locked; verify that its previous publisher stopped before removing the lock"
    end
  end

  defp rotate(owner) do
    validate_output!()
    previous = File.read(@env_path)

    try do
      result =
        Repo.transaction(fn ->
          # The database lock also serializes writers from other local checkouts.
          Repo.query!("SELECT pg_advisory_xact_lock($1)", [7_391_204_018])
          seed!(owner)
        end)

      case result do
        {:ok, _seeded} -> result
        {:error, _reason} -> raise "seed key transaction rolled back"
      end
    rescue
      error in DBConnection.ConnectionError ->
        # Losing the COMMIT response does not establish whether it committed.
        # Retain both output and lock rather than guess which key is active.
        reraise error, __STACKTRACE__

      error ->
        stacktrace = __STACKTRACE__
        restore_previous!(previous)
        {:error, error, stacktrace}
    end
  end

  defp restore_previous!({:ok, bytes}) do
    if File.read(@env_path) != {:ok, bytes}, do: publish_bytes!(bytes)
  end

  defp restore_previous!({:error, :enoent}) do
    case File.rm(@env_path) do
      :ok -> :ok
      {:error, :enoent} -> :ok
      {:error, _reason} -> raise "seed output rollback failed; output lock retained"
    end
  end

  defp seed!(owner) do
    scope = Scope.for_user(owner, ["instance_owner"])
    pool = ensure_pool!(owner)
    revoked = revoke_seed_keys!(scope, pool)

    {:ok, %{api_key: api_key, raw_key: raw_key}} =
      Access.create_api_key(scope, pool, %{
        display_name: "Dev real traffic key",
        metadata: %{labels: ["dev", "real-traffic"], dev_seed: @seed_key, operator_notes: "Generated by local dev seeds"}
      })

    write_env!(pool, raw_key)
    %{pool: pool, api_key: api_key, revoked_api_keys: revoked, env_path: @env_path}
  end

  defp ensure_pool!(owner) do
    case Repo.get_by(Pool, slug: @pool_slug) do
      %Pool{status: "active"} = pool ->
        pool

      %Pool{} ->
        raise "Pool #{@pool_slug} exists but is not active; reactivate or remove it first"

      nil ->
        timestamp = DateTime.utc_now() |> DateTime.truncate(:microsecond)

        %Pool{}
        |> Pool.changeset(%{
          slug: @pool_slug,
          name: @pool_name,
          status: "active",
          created_by_user_id: owner.id,
          created_at: timestamp,
          updated_at: timestamp
        })
        |> Repo.insert!()
    end
  end

  defp revoke_seed_keys!(scope, %Pool{id: pool_id}) do
    from(key in APIKey,
      where: key.pool_id == ^pool_id and key.status == "active" and fragment("?->>?", key.metadata, "dev_seed") == @seed_key
    )
    |> Repo.all()
    |> Enum.map(fn key ->
      {:ok, _revoked} = Access.revoke_api_key(scope, key)
      key.id
    end)
    |> length()
  end

  defp ensure_private_directory! do
    File.mkdir_p!(Path.dirname(@bootstrap_dir))

    case File.mkdir(@bootstrap_dir) do
      :ok -> File.chmod!(@bootstrap_dir, 0o700)
      {:error, :eexist} -> :ok
      {:error, _reason} -> raise "seed output requires a private directory"
    end

    case File.lstat(@bootstrap_dir) do
      {:ok, %File.Stat{type: :directory, mode: mode}} when Bitwise.band(mode, 0o777) == 0o700 -> :ok
      _unsafe -> raise "seed output requires a private directory"
    end
  end

  defp validate_output! do
    case File.lstat(@env_path) do
      {:error, :enoent} -> :ok
      {:ok, %File.Stat{type: :regular, mode: mode}} when Bitwise.band(mode, 0o777) == 0o600 -> :ok
      _unsafe -> raise "seed output must be a private regular file"
    end
  end

  defp write_env!(pool, raw_key) do
    validate_output!()
    publish_bytes!("CODEX_POOLER_REAL_TRAFFIC_API_KEY=#{raw_key}\nCODEX_POOLER_REAL_TRAFFIC_POOL_SLUG=#{pool.slug}\n")
  end

  defp publish_bytes!(bytes) do
    temporary = @env_path <> "." <> Ecto.UUID.generate()

    try do
      {:ok, "0600"} = PrivateFile.write(temporary, bytes)
      File.rename!(temporary, @env_path)
    after
      File.rm(temporary)
    end
  end
end
